# Generated by Django 5.2.7 on 2025-12-13 20:15

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Premium Boer Goat Buck'", max_length=200)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.CharField(help_text="e.g., '2 years' or '6 months'", max_length=50)),
                ('weight', models.CharField(blank=True, help_text="e.g., '45kg'", max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('mixed', 'Mixed (Group)')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('location', models.CharField(max_length=200)),
                ('is_sold', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('health_status', models.TextField(help_text='Current health condition')),
                ('vaccination_history', models.JSONField(blank=True, default=list, help_text='List of vaccines received')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='api.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='livestock', to='api.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Show as main image in gallery')),
                ('aspect_ratio', models.FloatField(default=1.0, help_text='Width / Height ratio for masonry layout')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.livestock')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
