# Generated by Django 5.2.7 on 2025-12-20 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactinquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('entry_page', models.CharField(max_length=500)),
                ('exit_page', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['first_visit'], name='api_visitor_first_v_2a8e89_idx'), models.Index(fields=['last_activity'], name='api_visitor_last_ac_672b37_idx'), models.Index(fields=['country'], name='api_visitor_country_c37bbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Browser session identifier', max_length=64)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('livestock_view', 'Livestock View')], default='page_view', max_length=20)),
                ('referrer', models.URLField(blank=True, max_length=1000, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='api.livestock')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='api_pagevie_created_772519_idx'), models.Index(fields=['session_id', 'created_at'], name='api_pagevie_session_e23f4a_idx'), models.Index(fields=['path', 'created_at'], name='api_pagevie_path_e9e8ec_idx'), models.Index(fields=['livestock', 'created_at'], name='api_pagevie_livesto_908e17_idx'), models.Index(fields=['event_type', 'created_at'], name='api_pagevie_event_t_fb407b_idx')],
            },
        ),
    ]
