# Generated by Django 5.2.7 on 2025-12-20 12:13

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_visitor_tracking_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Egg Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EggMediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Show as main image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('aspect_ratio', models.FloatField(default=1.0, help_text='Width / Height ratio for layout')),
            ],
            options={
                'verbose_name': 'Egg Media Asset',
                'verbose_name_plural': 'Egg Media Assets',
                'ordering': ['order', '-is_primary', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pageview',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('livestock_view', 'Livestock View'), ('egg_view', 'Egg View')], default='page_view', max_length=20),
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Fresh Farm Chicken Eggs'", max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('breed', models.CharField(blank=True, help_text="e.g., 'Rhode Island Red', 'Broiler'", max_length=100)),
                ('egg_type', models.CharField(choices=[('table', 'Table Eggs'), ('fertilized', 'Fertilized/Hatching'), ('organic', 'Organic'), ('free_range', 'Free Range')], default='table', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large'), ('jumbo', 'Jumbo')], default='medium', max_length=20)),
                ('packaging', models.CharField(choices=[('crate_30', 'Crate (30 eggs)'), ('tray_30', 'Tray (30 eggs)'), ('tray_12', 'Tray (12 eggs)'), ('half_crate_15', 'Half Crate (15 eggs)'), ('custom', 'Custom')], default='crate_30', max_length=20)),
                ('eggs_per_unit', models.PositiveIntegerField(default=30, help_text='Number of eggs per package')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per package', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text='Number of packages in stock')),
                ('production_date', models.DateField(help_text='Date eggs were produced/laid')),
                ('expiry_date', models.DateField(help_text='Best before date')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_eggs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='eggs', to='api.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pageview',
            name='egg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='api.egg'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['egg', 'created_at'], name='api_pagevie_egg_id_417e92_idx'),
        ),
        migrations.AddField(
            model_name='egg',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eggs', to='api.eggcategory'),
        ),
        migrations.AddField(
            model_name='eggmediaasset',
            name='egg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.egg'),
        ),
        migrations.AddIndex(
            model_name='egg',
            index=models.Index(fields=['is_available', 'created_at'], name='api_egg_is_avai_6c1cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='egg',
            index=models.Index(fields=['category', 'is_available'], name='api_egg_categor_2117f5_idx'),
        ),
        migrations.AddIndex(
            model_name='egg',
            index=models.Index(fields=['production_date'], name='api_egg_product_29a43c_idx'),
        ),
        migrations.AddIndex(
            model_name='egg',
            index=models.Index(fields=['expiry_date'], name='api_egg_expiry__64a30e_idx'),
        ),
        migrations.AddIndex(
            model_name='egg',
            index=models.Index(fields=['egg_type'], name='api_egg_egg_typ_f00e7e_idx'),
        ),
    ]
