# Generated by Django 5.2.7 on 2025-12-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eggcategory_eggmediaasset_alter_pageview_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Best before date', null=True),
        ),
        migrations.AlterField(
            model_name='egg',
            name='production_date',
            field=models.DateField(blank=True, help_text='Date eggs were produced/laid', null=True),
        ),
    ]
