# Generated by Django 5.2.7 on 2026-07-23 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_denull_pageview_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('common_breeds', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='lucide-react icon name for the frontend', max_length=40)),
                ('source_note', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='egg',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per package', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='age',
            field=models.CharField(blank=True, help_text="e.g., '2 years' or '6 months'", max_length=50),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('mixed', 'Mixed (Group)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='VaccinationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('vaccine', 'Vaccine'), ('deworm', 'Deworming'), ('vitamin', 'Vitamin / Supplement'), ('management', 'Management')], default='vaccine', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('protects_against', models.CharField(blank=True, max_length=200)),
                ('age_offset_days', models.IntegerField(help_text='Age at administration, in days from birth/hatch (0 = day-old)')),
                ('age_label', models.CharField(max_length=60)),
                ('repeat_interval_days', models.PositiveIntegerField(blank=True, help_text='If the dose recurs, days between doses', null=True)),
                ('route', models.CharField(choices=[('sc', 'Subcutaneous'), ('im', 'Intramuscular'), ('oral', 'Oral / Drinking water'), ('eye', 'Eye drop / Intranasal'), ('spray', 'Spray'), ('wing', 'Wing web'), ('topical', 'Topical / Pour-on'), ('other', 'Other')], default='sc', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_core', models.BooleanField(default=True, help_text='Core (strongly recommended) vs optional/regional')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.species')),
            ],
            options={
                'ordering': ['species', 'age_offset_days', 'sort_order'],
                'indexes': [models.Index(fields=['species', 'age_offset_days'], name='api_vaccina_species_472fea_idx')],
            },
        ),
    ]
