# Generated by Django 5.2.7 on 2026-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_contactinquiry_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(choices=[('purchase', 'Livestock Purchase'), ('investment', 'Investment Inquiry'), ('partnership', 'Partnership Opportunity'), ('academy', 'Future Farmers Academy'), ('training', 'Training & Workshops'), ('visit', 'Schedule a Visit'), ('support', 'General Support'), ('other', 'Other')], max_length=20),
        ),
    ]
