# Generated by Django 5.2.7 on 2026-09-02 13:51

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_contactinquiry_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(blank=True, help_text='One or two lines shown on the course card')),
                ('topic', models.CharField(choices=[('breeding', 'Breeding & improved genetics'), ('nutrition', 'Feeding & nutrition'), ('health', 'Disease prevention'), ('management', 'Farm management & records')], default='management', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='course material')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'sort_order'], name='api_coursem_is_publ_a2d386_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=200)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_figures_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_name', models.CharField(db_index=True, max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('phone_normalized', models.CharField(db_index=True, editable=False, max_length=16)),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('cohort', models.CharField(blank=True, max_length=80)),
                ('programme', models.CharField(blank=True, max_length=120)),
                ('issued_on', models.DateField()),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='certificate')),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_on', 'holder_name'],
                'indexes': [models.Index(fields=['is_published', '-issued_on'], name='api_certifi_is_publ_b42f11_idx')],
            },
        ),
    ]
