# Generated by Django 5.2.7 on 2026-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_coursematerial_sitefigure_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Pages, or slides for a deck', null=True),
        ),
    ]
