import { Metadata } from "next"
import Link from "next/link"
import { LegalLayout, LegalSection } from "@/components/legal/legal-layout"

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of the Green Livestock Africa website, tools, marketplace, and educational resources.",
}

export default function TermsPage() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Terms of Service"
      lastUpdated="23 July 2026"
      intro="These terms govern your use of the Green Livestock Africa website and services. By using the site — browsing listings, reading our resources, using the Herd Health Card, or sending an inquiry — you agree to these terms. Please read them carefully."
    >
      <LegalSection heading="Who we are">
        <p>
          Green Livestock Africa is an education-first platform that trains, equips, and
          supports livestock farmers across Africa, and connects trained farmers with a
          marketplace, inputs, sponsors, and partners. “We”, “us”, and “our” refer to
          Green Livestock Africa.
        </p>
      </LegalSection>

      <LegalSection heading="Using our services">
        <p>You agree to use the platform lawfully and responsibly. You agree not to:</p>
        <ul>
          <li>Provide false, misleading, or fraudulent information in inquiries or forms.</li>
          <li>Interfere with, disrupt, or attempt to gain unauthorised access to the platform.</li>
          <li>Use the site to infringe the rights of others or for any unlawful purpose.</li>
          <li>Copy, scrape, or reproduce our content for commercial use without permission.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Educational content and the Herd Health Card">
        <p>
          Our workshops, articles, tools, and the vaccination schedules generated by the
          Herd Health Card are provided for general educational guidance. They are
          compiled from standard veterinary references and are not a substitute for
          advice from a licensed veterinarian who knows your herd, region, and
          circumstances. Always confirm health, breeding, and treatment decisions with a
          qualified professional. We are not liable for outcomes resulting from reliance
          on general guidance.
        </p>
      </LegalSection>

      <LegalSection heading="Listings, inquiries, and the marketplace">
        <p>
          Livestock, egg, and input listings are shown for information. Availability,
          pricing, and specifics are confirmed directly with our team — many items are
          inquiry-based rather than instantly purchasable. Submitting an inquiry or
          request does not create a binding contract; any sale, sourcing, or supply is
          subject to a separate agreement confirmed between you and us. We aim to keep
          listings accurate but do not warrant that all details are complete or current.
        </p>
      </LegalSection>

      <LegalSection heading="Partnerships and sponsorship">
        <p>
          Expressions of interest in partnering with or sponsoring our work are the start
          of a conversation, not a commitment. Any partnership, funding, or sponsorship
          arrangement is governed by a separate written agreement between the parties.
        </p>
      </LegalSection>

      <LegalSection heading="Intellectual property">
        <p>
          The Green Livestock Africa name, logo, content, and design are our property or
          used with permission, and are protected by applicable laws. You may view and
          share our public content for personal, non-commercial purposes with
          attribution, but you may not reproduce it commercially without our written
          consent.
        </p>
      </LegalSection>

      <LegalSection heading="Third-party services and links">
        <p>
          Our site relies on third-party providers and may link to external sites, such as
          our social media pages. We are not responsible for the content or practices of
          third parties. Your use of their services is governed by their own terms.
        </p>
      </LegalSection>

      <LegalSection heading="Disclaimers and limitation of liability">
        <p>
          The platform is provided “as is” and “as available”. To the fullest extent
          permitted by law, we disclaim warranties of any kind and are not liable for
          indirect, incidental, or consequential losses arising from your use of the
          site, its tools, or its content. Nothing in these terms limits any liability
          that cannot be excluded under applicable law.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to these terms">
        <p>
          We may update these terms as our services evolve. Changes take effect when
          posted, with the “last updated” date revised above. Continuing to use the site
          after changes means you accept the updated terms.
        </p>
      </LegalSection>

      <LegalSection heading="Governing law">
        <p>
          These terms are governed by the laws of the Federal Republic of Nigeria, and any
          disputes are subject to the jurisdiction of its courts.
        </p>
      </LegalSection>

      <LegalSection heading="Contact us">
        <p>
          Questions about these terms? Reach us at{" "}
          <a href="mailto:info@greenlivestockafrica.com">info@greenlivestockafrica.com</a>,
          call +234 915 5467 776, or write to Green Livestock Africa, Odhiogbor Road, IGP
          Checkpoint Ele-uma, Mbiama, Rivers State, Nigeria. You can also reach us through
          our <Link href="/contact">contact page</Link>.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}
